project:
  type: website
  output-dir: outputs

website:
  title: "Заметки"
  navbar:
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/axchizhov/
      - icon: linkedin
        href: https://www.linkedin.com/feed/
format:
  html:
    theme: cosmo
    # css: styles.css