project:
  type: website
  output-dir: outputs

website:
  title: "Заметки"
  navbar:
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/axchizhov/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    # css: styles.css